### ISSUE TITLE
No issue just a question 

### ISSUE THREAD

**Issue by DisplayedAim** [freshollie/hqhero#1]
Hey there, I love what you've done here. I've been working on a small little project and was wondering whether you'd like to hop aboard, add me on discord - DisplayedAim#0001

**Comment by freshollie** [comment]
This kind of thing would be more useful as an email. Please send me more details via email.

**Comment by shaunTX** [comment]
The bot didn't work during the 9pm ET game on Thursday (Disney themed). Even now it's saying game was 7 hours ago, instead of showing how many hours until next game.

**Comment by freshollie** [comment]
Fixed.
