### ISSUE TITLE
Germany games no longer run

### ISSUE THREAD

**Issue by Chew** [freshollie/hqhero#2]
As of now, Germany games don't run, and going to `/de` just shows the US games, as germany can only play US games (possibly UK, idk) games.

**Comment by freshollie** [comment]
I will look into this.

**Comment by freshollie** [comment]
I have fixed the `get_bearer` script in https://github.com/freshollie/herobrain, and updated the bearer token. However, this was not the issue.

As per their twitter. German HQ trivia games are currently not running. https://twitter.com/hqtriviade/status/1028294030176739329

**Comment by Chew** [comment]
ye this was my problem, UK and DE dont even work anymore. they both say "next game months ago" or something, only US tab shows answers now

**Comment by freshollie** [comment]
UK is fixed. Germany don't run games, as stated before, so I don't update their token.
