### ISSUE TITLE
Only predicting answers for 1 or 2 questions a game. 

### ISSUE THREAD

**Issue by shaunTX** [freshollie/hqhero#5]
Bot is only predicting answers for 1 or 2 questions a game. It just highlights the first answer in green and all choices say 0%

**Comment by freshollie** [comment]
Something's gone wrong. Will hopefully fix tonight.

**Comment by freshollie** [comment]
Fixed by https://github.com/freshollie/herobrain/commit/51057b3dbfec3f91cbd6bba55a0a6cb6eb92457b

**Comment by ombharti7** [comment]
What is the accuracy of the bot?
